### ISSUE TITLE
Consider adding `binutils` as make dependency

### ISSUE THREAD

**Issue by tukusejssirs** [lubo/archlinux-eidklient#2]
You use `strings` (from `binutils` package) to get the eID Client version number from its binary. I think it should be listed in the `makedepends` variable. WDYT? :thinking:

https://github.com/lubo/archlinux-eidklient/blob/45f5e7e2f860ecdbb201c8834a694756c8530126/PKGBUILD#L37

**Comment by lubo** [comment]
According to https://wiki.archlinux.org/title/PKGBUILD#makedepends:

>The package `base-devel` is assumed to be already installed when building with makepkg. Dependencies of this package should not be included in `makedepends` array.
